[package]
name = "gitpersona-desktop"
version = "0.6.0"
edition = "2024"
description = "GitPersona desktop application"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
gitpersona = { path = "../.." }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"

